// Voxel items and props: the two kinds, side by side.
//
// On the bench, things out of the game. A Minecraft item is a flat 16x16
// sprite, and what the game shows you is that sprite extruded -- so for a
// voxel renderer it is not a picture of an item, it is an item. Every texel
// becomes a couple of voxels and the result shades, shadows and reflects like
// any other geometry.
//
// Around it, things that are ours. A barrel modelled with the same shape::
// primitives that build terrain and then captured off the lattice; a lantern
// drawn as text in the source; a crystal generated by a formula. All three
// end up as the same VoxelModel, and none of them is bound to the block grid:
// they rotate freely and scale to whatever size the scene wants.
//
//   scene_props          full quality
//   scene_props draft    small and fast
//   scene_props bare     ignore game assets, custom props only
#include "engine/assets/asset_source.hpp"
#include "engine/assets/blocks/block_textures.hpp"
#include "engine/core/png.hpp"
#include "engine/prop/item.hpp"
#include "engine/prop/prop_set.hpp"
#include "engine/prop/voxelize.hpp"
#include "engine/render/post/denoise.hpp"
#include "engine/render/post/effects.hpp"
#include "engine/render/trace/pathtrace.hpp"
#include "engine/scene/scene.hpp"
#include "engine/sprite/font.hpp"
#include "engine/sprite/sprite_set.hpp"
#include "engine/sprite/text.hpp"
#include "engine/world/shapes.hpp"
#include "scenes/common/palette.hpp"

#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

using namespace blocky;

namespace {

constexpr float kBenchTop = 6.0f;

void buildRoom(World& world) {
    world.fillBox({-24, -2, -20}, {24, 0, 20}, palette::Stone);
    shape::replace(world, {-24, 0, -20}, {24, 0, 20}, palette::Stone, palette::Cobblestone);

    // Back wall, with a brick course at eye level to break up the grey.
    world.fillBox({-24, 1, -20}, {24, 18, -18}, palette::Cobblestone);
    world.fillBox({-24, 8, -20}, {24, 9, -18}, palette::Bricks);

    // The bench the items stand on.
    world.fillBox({-14, 1, -3}, {14, int(kBenchTop) - 1, 2}, palette::OakPlanks);
    world.fillBox({-14, int(kBenchTop) - 1, -3}, {14, int(kBenchTop) - 1, 2}, palette::OakLog);

    // Lanterns recessed into the wall. Sat on the bench they read as two
    // white cubes among the items, which is exactly what they are.
    for (int x : {-11, 0, 11}) {
        world.set({x, 12, -18}, palette::Glowstone);
        world.set({x, 12, -17}, palette::Air);
    }
}

// ------------------------------------------------- custom prop #1: captured
// Modelled with the ordinary shape primitives, in a scratch world, then
// lifted off the lattice. Everything in shape:: is available to a prop this
// way -- ellipsoids, cylinders, erosion, the clipboard.
VoxelModel buildBarrel() {
    World scratch(palette::registry());

    shape::cylinder(scratch, {12.0f, 0.0f, 12.0f}, {0, 1, 0}, 7.0f, 18.0f, palette::OakPlanks);
    // Hollow it out from the top, leaving a floor.
    shape::cylinder(scratch, {12.0f, 3.0f, 12.0f}, {0, 1, 0}, 5.6f, 16.0f, palette::Air);

    // Iron hoops.
    shape::torus(scratch, {12.0f, 3.5f, 12.0f}, {0, 1, 0}, 7.0f, 0.9f, palette::IronBlock);
    shape::torus(scratch, {12.0f, 14.5f, 12.0f}, {0, 1, 0}, 7.0f, 0.9f, palette::IronBlock);

    return voxelize::fromWorld(scratch, {0, 0, 0}, {24, 20, 24});
}

// ---------------------------------------------------- custom prop #2: drawn
// Small enough that a primitive would be the wrong tool. Drawn as text so a
// wrong voxel is a wrong character, visible in the source.
VoxelModel buildLantern() {
    VoxelMaterial iron;
    iron.albedo = srgbToLinear(Vec3{0.42f, 0.44f, 0.48f});
    iron.roughness = 0.35f;
    iron.metallic = 1.0f;

    VoxelMaterial glass;
    glass.albedo = srgbToLinear(Vec3{1.0f, 0.86f, 0.55f});
    glass.emission = {14.0f, 9.0f, 3.4f};

    // Corner posts only between the plates. The first draft walled the glass
    // in on all four sides, which is airtight and completely dark: the glow
    // had nowhere to go and the lantern rendered as a black lump.
    return voxelize::fromLayers(
        {
            {".###.", "#####", "#####", "#####", ".###."},  // y0  base
            {".....", ".#~#.", ".~~~.", ".#~#.", "....."},  // y1  glass, posts at the corners
            {".....", ".#~#.", ".~~~.", ".#~#.", "....."},  // y2
            {".....", ".#~#.", ".~~~.", ".#~#.", "....."},  // y3
            {".###.", "#####", "#####", "#####", ".###."},  // y4  cap
            {".....", "..#..", ".#.#.", "..#..", "....."},  // y5  handle
        },
        {{'#', iron}, {'~', glass}});
}

// ------------------------------------------------ custom prop #3: generated
// No world, no text: just a formula writing voxels. A model is a plain grid,
// so anything that can decide "solid or not" can author one.
VoxelModel buildCrystal(int height) {
    VoxelModel model;
    model.resize({9, height, 9});

    VoxelMaterial core;
    core.albedo = srgbToLinear(Vec3{0.36f, 0.82f, 0.92f});
    core.emission = {1.6f, 5.2f, 6.4f};
    core.roughness = 0.15f;

    VoxelMaterial shell;
    shell.albedo = srgbToLinear(Vec3{0.20f, 0.52f, 0.68f});
    shell.roughness = 0.22f;
    shell.metallic = 0.0f;

    uint16_t coreSlot = model.addMaterial(core);
    uint16_t shellSlot = model.addMaterial(shell);

    for (int y = 0; y < height; ++y) {
        // Broad at the foot, tapering to a point. The first version was a
        // sine bulging in the middle, which renders as a blue pebble.
        float along = float(y) / float(height - 1);
        float radius = 4.0f * std::pow(1.0f - along, 0.6f);

        for (int z = 0; z < 9; ++z) {
            for (int x = 0; x < 9; ++x) {
                float dx = float(x) - 4.0f, dz = float(z) - 4.0f;
                float d = std::sqrt(dx * dx + dz * dz);
                if (d > radius) continue;
                model.set({x, y, z}, d < radius - 1.4f ? coreSlot : shellSlot);
            }
        }
    }

    model.trim();
    return model;
}

} // namespace

int main(int argc, char** argv) {
    bool draft = false, bare = false;
    for (int i = 1; i < argc; ++i) {
        if (std::strcmp(argv[i], "draft") == 0) draft = true;
        if (std::strcmp(argv[i], "bare") == 0) bare = true;
    }

    Scene scene(palette::registry());
    buildRoom(scene.world);

    // ------------------------------------------------------------- assets
    AssetSource source;
    BlockTextureLibrary blockTextures;
    Font font;

    std::string jar;
    bool haveAssets = false;
    if (!bare) {
        jar = AssetSource::findClientJar();
        haveAssets = !jar.empty() && source.open(jar, nullptr);
    }

    if (haveAssets) {
        if (blockTextures.load(source, scene.world.registry(), palette::minecraftRules(), nullptr)) {
            scene.blockTextures = &blockTextures;
        }
        if (!font.loadFromSource(source, Font::kMinecraftAscii, nullptr)) font.useBuiltin();
        std::printf("[props] assets: %s\n", jar.c_str());
    } else {
        font.useBuiltin();
        std::printf("[props] no game assets: custom props only\n");
    }

    // --------------------------------------------------------- the models
    // Every model must outlive the set, which only ever holds pointers.
    VoxelModel barrel = buildBarrel();
    VoxelModel lantern = buildLantern();
    VoxelModel crystal = buildCrystal(19);

    // Item textures are all metal-free by default; the shiny ones say so.
    struct ItemSpec {
        const char* name;
        float roughness;
        float metallic;
    };
    const ItemSpec kItems[] = {
        {"diamond_sword", 0.30f, 0.0f}, {"golden_pickaxe", 0.25f, 1.0f},
        {"apple", 0.55f, 0.0f},         {"gold_ingot", 0.18f, 1.0f},
        {"bread", 0.85f, 0.0f},         {"ender_pearl", 0.20f, 0.0f},
        {"iron_ingot", 0.24f, 1.0f},    {"emerald", 0.15f, 0.0f},
    };
    constexpr size_t kItemCount = sizeof(kItems) / sizeof(kItems[0]);

    std::vector<VoxelModel> itemModels(kItemCount);
    std::vector<bool> itemLoaded(kItemCount, false);
    size_t loaded = 0;

    if (haveAssets) {
        for (size_t i = 0; i < kItemCount; ++i) {
            item::ItemOptions options;
            options.roughness = kItems[i].roughness;
            options.metallic = kItems[i].metallic;

            std::string error;
            if (!item::loadByName(source, kItems[i].name, itemModels[i], options, &error)) {
                std::printf("[props] skipped %s: %s\n", kItems[i].name, error.c_str());
                continue;
            }
            itemLoaded[i] = true;
            ++loaded;
        }
        std::printf("[props] %zu of %zu item textures extruded\n", loaded, kItemCount);
    }

    // --------------------------------------------------------- the placing
    PropSet props;

    // The row on the bench. Standing upright, each turned a little so the
    // line does not read as a decal.
    for (size_t i = 0; i < kItemCount; ++i) {
        if (!itemLoaded[i]) continue;

        Prop prop;
        prop.model = &itemModels[i];
        prop.position = {-12.6f + float(i) * 3.25f, kBenchTop, -0.5f};
        prop.voxelSize = 1.0f / 9.0f;  // a shade under two blocks tall
        prop.anchor = Prop::Anchor::BottomCentre;
        prop.yawDegrees = -18.0f + float(i % 3) * 17.0f;
        props.add(prop);
    }

    // A giant one behind the bench, driven into the floor: the same model at
    // eight times the voxel size, to show that nothing here is tied to the
    // block grid.
    if (itemLoaded[0]) {
        Prop giant;
        giant.model = &itemModels[0];
        giant.position = {-19.0f, 0.5f, -9.0f};
        giant.voxelSize = 0.70f;
        giant.anchor = Prop::Anchor::BottomCentre;
        giant.yawDegrees = 34.0f;
        giant.rollDegrees = 11.0f;
        props.add(giant);
    }

    // The custom ones, on the floor in front of the bench.
    {
        Prop cask;
        cask.model = &barrel;
        cask.position = {-10.5f, 1.0f, 6.0f};
        cask.voxelSize = 0.165f;
        cask.yawDegrees = 22.0f;
        props.add(cask);

        Prop tipped = cask;
        tipped.position = {-4.6f, 2.3f, 7.6f};
        tipped.rollDegrees = 90.0f;   // on its side, which a lattice could not do
        tipped.yawDegrees = -34.0f;
        props.add(tipped);

        Prop light;
        light.model = &lantern;
        light.position = {1.6f, 1.0f, 6.8f};
        light.voxelSize = 0.34f;
        light.yawDegrees = -12.0f;
        props.add(light);

        // The same lantern again, small, up on the bench.
        Prop small = light;
        small.position = {12.2f, kBenchTop, 0.2f};
        small.voxelSize = 0.16f;
        small.yawDegrees = 30.0f;
        props.add(small);

        Prop shard;
        shard.model = &crystal;
        shard.position = {7.4f, 1.0f, 7.2f};
        shard.voxelSize = 0.22f;
        shard.yawDegrees = 40.0f;
        shard.pitchDegrees = 9.0f;
        props.add(shard);

        // A tinted copy: one model, two colours, no second grid.
        Prop rose = shard;
        rose.position = {11.6f, 1.0f, 4.4f};
        rose.voxelSize = 0.15f;
        rose.yawDegrees = -25.0f;
        rose.tint = {1.5f, 0.55f, 0.75f};
        rose.emissionScale = {2.4f, 0.5f, 0.9f};
        props.add(rose);
    }

    props.build();
    scene.props = &props;

    std::printf("[props] %zu placed, %llu voxels, bvh depth %d\n", props.size(),
                (unsigned long long)props.voxelCount(), props.bvh().maxDepth());

    // ------------------------------------------------------------- labels
    SpriteSet sprites;
    const Vec3 eye{13.0f, 13.0f, 24.5f};
    {
        TextStyle style;
        style.height = 1.05f;
        style.color = srgbToLinear(Vec3{0.96f, 0.91f, 0.78f});
        style.emission = {0.75f, 0.66f, 0.46f};
        // With no game files the bench is empty, and a sign over it saying
        // otherwise would just be wrong.
        const char* heading = loaded > 0 ? "FROM THE GAME" : "NO GAME ASSETS";
        sprites.add(text::facing(font, heading, {-0.5f, 11.4f, -4.0f}, eye, style));

        TextStyle small = style;
        small.height = 0.52f;
        small.emission = {0.34f, 0.30f, 0.22f};
        sprites.add(text::facing(font, "ours: captured, drawn, generated", {1.5f, 2.5f, 12.0f},
                                 eye, small));
    }
    sprites.build();
    scene.sprites = &sprites;

    // -------------------------------------------------------------- camera
    scene.camera.projection = Camera::Projection::Perspective;
    scene.camera.fovY = radians(44.0f);
    scene.camera.lookAt(eye, {-1.5f, 5.2f, 1.5f});
    scene.camera.aperture = draft ? 0.0f : 0.16f;
    scene.camera.focusOn({-2.0f, 7.0f, -0.5f});

    // --------------------------------------------------------------- light
    scene.sun.direction = normalize(Vec3{-0.46f, 0.62f, 0.64f});
    scene.sun.color = {1.0f, 0.88f, 0.70f};
    scene.sun.intensity = 9.5f;
    scene.sun.angularRadiusDegrees = 1.5f;

    scene.sky.zenith = {0.13f, 0.24f, 0.52f};
    scene.sky.horizon = {0.58f, 0.62f, 0.78f};
    scene.sky.intensity = 1.0f;
    scene.ambientStrength = 0.8f;

    // -------------------------------------------------------------- render
    PathSettings settings;
    settings.width = draft ? 720 : 1500;
    settings.height = draft ? 450 : 940;
    settings.samplesPerPixel = draft ? 28 : 140;
    settings.maxBounces = draft ? 4 : 8;

    RenderStats stats;
    RenderTargets targets;
    Image frame = renderPath(scene, settings, &stats, &targets);
    frame = denoise(targets, {});

    BloomSettings bloom;
    bloom.threshold = 1.2f;
    bloom.intensity = 0.07f;
    applyBloom(frame, bloom);

    GradeSettings grade;
    grade.contrast = 1.05f;
    grade.saturation = 1.06f;
    grade.temperature = 0.06f;
    applyGrade(frame, grade);

    applyVignette(frame, {});
    applyGrain(frame, 0.009f);

    ToneParams tone;
    tone.curve = Tonemap::ACES;

    const char* path = draft ? "out/props_draft.png" : "out/props.png";
    pngSave(path, frame, tone, nullptr);
    std::printf("[props] wrote %s\n", path);
    return 0;
}
