// Generated by BlockyEngine forge. Do not edit by hand: the editor writes
// this file whole, so the next export throws any change here away.
//
// 5 x 4 x 3 voxels, 3 materials.
#pragma once

#include "engine/prop/voxelize.hpp"

inline blocky::VoxelModel buildEmittedProbe() {
    using blocky::Vec3;
    using blocky::VoxelMaterial;

    return blocky::voxelize::fromLayers(
        {
            // y = 0
            {
                "#####",
                ".....",
                "....."
            },
            // y = 1
            {
                "#....",
                ".....",
                "....+"
            },
            // y = 2
            {
                "*....",
                "..*..",
                "....."
            },
            // y = 3
            {
                "*....",
                ".....",
                "....."
            }
        },
        {
            {'#', VoxelMaterial{.albedo = Vec3{0.147318989f, 0.162647218f, 0.187316656f}, .emission = Vec3{0.0f, 0.0f, 0.0f},
                            .roughness = 1.0f, .metallic = 0.0f}},  // #6b7078
            {'*', VoxelMaterial{.albedo = Vec3{0.955104649f, 0.587016404f, 0.0331047624f}, .emission = Vec3{0.0f, 0.0f, 0.0f},
                            .roughness = 0.280000001f, .metallic = 1.0f}},  // #fac933
            {'+', VoxelMaterial{.albedo = Vec3{0.692071199f, 0.0469641946f, 0.00854038261f}, .emission = Vec3{4.0f, 0.899999976f, 0.200000003f},
                            .roughness = 1.0f, .metallic = 0.0f}}  // #d93d17
        });
}
