// Generated by BlockyEngine forge. Do not edit by hand: the editor writes
// this file whole, so the next export throws any change here away.
//
// 6 x 4 texels, 3 colours.
#pragma once

#include "engine/assets/pixel_art.hpp"

inline blocky::ImageU8 buildEmittedSwatch() {
    using blocky::ImageU8;

    return blocky::pixelart::fromRows(
        {
            "######",
            "*.....",
            "*.+...",
            ".....+"
        },
        {
            {'#', ImageU8::RGBA{255, 170, 40, 255}},  // #ffaa28
            {'*', ImageU8::RGBA{26, 29, 34, 255}},  // #1a1d22
            {'+', ImageU8::RGBA{120, 200, 255, 128}}  // #78c8ff
        });
}
