// Generated by BlockyEngine forge. Do not edit by hand: the editor writes
// this file whole, so the next export throws any change here away.
//
// 3 sprites.
#pragma once

#include "engine/sprite/sprite.hpp"

#include <vector>

inline std::vector<blocky::Sprite> placeEmittedMotes(const blocky::Texture* texture = nullptr) {
    using blocky::Sprite;
    using blocky::Vec2;
    using blocky::Vec3;

    std::vector<Sprite> sprites;
    sprites.reserve(3);

    {
        Sprite sprite;
        sprite.position = Vec3{0.25f, 1.5f, -0.75f};
        sprite.size = Vec2{0.0799999982f, 0.0799999982f};
        sprite.tint = Vec3{0.692071199f, 0.638283253f, 0.447988421f};  // #d9d1b3
        sprite.texture = texture;
        sprites.push_back(sprite);
    }

    {
        Sprite sprite;
        sprite.position = Vec3{-1.25f, 0.5f, 2.0f};
        sprite.size = Vec2{0.140000001f, 0.200000003f};
        sprite.yawDegrees = 33.0f;
        sprite.pitchDegrees = -12.5f;
        sprite.rollDegrees = 7.0f;
        sprite.tint = Vec3{0.890005529f, 0.170644939f, 0.0100228256f};  // #f2731a
        sprite.emission = Vec3{4.0f, 1.20000005f, 0.300000012f};
        sprite.texture = texture;
        sprites.push_back(sprite);
    }

    {
        Sprite sprite;
        sprite.position = Vec3{3.0f, 2.25f, 0.0f};
        sprite.size = Vec2{1.0f, 0.5f};
        sprite.roughness = 0.400000006f;
        sprite.alphaCutoff = 0.25f;
        sprite.doubleSided = false;
        sprite.uvMin = Vec2{0.25f, 0.0f};
        sprite.uvMax = Vec2{0.75f, 1.0f};
        sprite.texture = texture;
        sprites.push_back(sprite);
    }

    return sprites;
}
